import React from 'react';
import { ShieldCheck, FileText, BookOpen, Layers, Lock, Cpu, Code } from 'lucide-react';

export const LegalDocsView: React.FC = () => {
  return (
    <div className="space-y-6 font-sans">
      {/* Header Banner */}
      <div className="glass-card rounded-3xl p-6 border border-dark-border">
        <div className="flex items-center space-x-4">
          <div className="w-12 h-12 rounded-2xl bg-brand-cyan/20 text-brand-cyan border border-brand-cyan/30 flex items-center justify-center">
            <FileText className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <h2 className="text-xl font-bold text-white tracking-tight">Legal Terms, Regulatory Framework & Technical Documentation</h2>
              <span className="text-[10px] font-bold px-2.5 py-0.5 rounded-full bg-brand-cyan/20 text-brand-cyan border border-brand-cyan/30">
                MiCA & Non-Custodial Docs
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Comprehensive legal disclaimers, MiCA alignment disclosures, technical architecture documentation, and README specifications.
            </p>
          </div>
        </div>
      </div>

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left 2 Cols: Comprehensive Legal & README Docs */}
        <div className="lg:col-span-2 space-y-6">
          {/* Section 1: Executive Legal Disclaimer */}
          <div className="glass-card rounded-3xl p-6 border border-dark-border space-y-4">
            <h3 className="font-bold text-white text-base flex items-center gap-2">
              <ShieldCheck className="w-5 h-5 text-brand-cyan" />
              1. Non-Custodial Telemetry & Legal Disclaimers
            </h3>

            <div className="text-xs text-slate-300 leading-relaxed space-y-3 font-sans">
              <p>
                <strong>Non-Custodial Architecture:</strong> ReputationOS operates exclusively as a read-only telemetry dashboard and autonomous security monitoring protocol. The platform never requests, stores, or accesses private keys, seed phrases, or un-encrypted signers.
              </p>
              <p>
                <strong>Financial Disclaimer:</strong> All reputation scores, risk levels, health factors, and AI security verdicts generated by ShadowGuard AI are provided strictly for informational and security audit purposes. They do not constitute financial advice, investment recommendations, or endorsement of any cryptographic asset or liquidity pool.
              </p>
              <p>
                <strong>Regulatory Compliance (MiCA & Travel Rule Alignment):</strong> ReputationOS adheres to the European Union Markets in Crypto-Assets (MiCA) regulation frameworks regarding transparent risk scoring, consumer protection, and non-custodial software dissemination.
              </p>
            </div>
          </div>

          {/* Section 2: Technical Architecture Documentation & README Specification */}
          <div className="glass-card rounded-3xl p-6 border border-dark-border space-y-4">
            <h3 className="font-bold text-white text-base flex items-center gap-2">
              <BookOpen className="w-5 h-5 text-brand-purple" />
              2. System Architecture Documentation & README Specification
            </h3>

            <div className="bg-dark-900 border border-dark-border rounded-2xl p-5 font-mono text-xs text-slate-300 space-y-4 whitespace-pre-line leading-relaxed">
              {`# ReputationOS (ShadowGuard AI Engine) - Technical README

## Overview
ReputationOS is an enterprise-grade Web3 reputation telemetry, smart contract security auditing, and autonomous risk scoring framework built with React, Vite, TypeScript, Tailwind CSS, and Lucide icons.

### Core Architectural Components
1. **ShadowGuard AI Reasoning Engine**: Continuously parses on-chain transaction bytecode, ERC20/ERC721 approvals, and EIP-712 Permit signatures to compute real-time risk scores (0-100 scale).
2. **Multi-Chain RPC Indexer Integration**: Interfaces with Etherscan, Solscan, Blockscout, Alchemy, and DexScreener APIs to stream real-time balance metrics across Ethereum, Base, Solana, Arbitrum, Polygon, and Sonic chains.
3. **Autonomous Background Agent Service**: An always-on background polling loop that monitors connected wallet addresses and sample addresses for unconfirmed mempool exploits, unverified proxy approvals, and phishing drainers.

### Security Model & EIP-1193 Safety Standards
- **Read-Only Telemetry**: The platform operates in strict read-only mode until the user explicitly initiates a transaction or contract approval revocation.
- **EIP-1193 Browser Provider Compatibility**: Native integration with RainbowKit, MetaMask, Rabby, Coinbase Wallet, and Phantom.
- **Cloudflare Shield Deployment**: Built for high-speed edge distribution via Cloudflare Pages and Workers with DDoS mitigation.

### License & Compliance
Distributed under the MIT Open Source License. Compliant with MiCA (Markets in Crypto-Assets) non-custodial software standards.`}
            </div>
          </div>
        </div>

        {/* Right Col: Quick Tech Disclosures */}
        <div className="space-y-6">
          <div className="glass-card rounded-3xl p-6 border border-dark-border space-y-4">
            <h3 className="font-bold text-white text-sm flex items-center gap-2">
              <Code className="w-4 h-4 text-brand-cyan" />
              Platform Stack Summary
            </h3>

            <div className="space-y-3 text-xs">
              <div className="p-3 bg-dark-800 rounded-xl border border-dark-border">
                <span className="text-slate-400 block font-semibold">Framework</span>
                <span className="text-white font-mono">React 18 • Vite 8 • TypeScript</span>
              </div>
              <div className="p-3 bg-dark-800 rounded-xl border border-dark-border">
                <span className="text-slate-400 block font-semibold">Styling Engine</span>
                <span className="text-white font-mono">Tailwind CSS • Glassmorphism</span>
              </div>
              <div className="p-3 bg-dark-800 rounded-xl border border-dark-border">
                <span className="text-slate-400 block font-semibold">Edge Deployment Target</span>
                <span className="text-white font-mono">Cloudflare Pages & Workers</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
